// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.Infrastructure.Persistence;

#nullable disable

namespace TicketingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260513013321_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2025, 12, 31, 20, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concierto de Rock",
                            Status = "Active",
                            Venue = "Estadio Municipal"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Number = 1,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            Number = 1,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Number = 2,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            Number = 2,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Number = 3,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            Number = 3,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Number = 4,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            Number = 4,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Number = 5,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            Number = 5,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Number = 6,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            Number = 6,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Number = 7,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000007"),
                            Number = 7,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Number = 8,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000008"),
                            Number = 8,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000009"),
                            Number = 9,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000009"),
                            Number = 9,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000010"),
                            Number = 10,
                            Row = "1",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000010"),
                            Number = 10,
                            Row = "1",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000011"),
                            Number = 1,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000011"),
                            Number = 1,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000012"),
                            Number = 2,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000012"),
                            Number = 2,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000013"),
                            Number = 3,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000013"),
                            Number = 3,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000014"),
                            Number = 4,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000014"),
                            Number = 4,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000015"),
                            Number = 5,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000015"),
                            Number = 5,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000016"),
                            Number = 6,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000016"),
                            Number = 6,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000017"),
                            Number = 7,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000017"),
                            Number = 7,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000018"),
                            Number = 8,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000018"),
                            Number = 8,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000019"),
                            Number = 9,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000019"),
                            Number = 9,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000020"),
                            Number = 10,
                            Row = "2",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000020"),
                            Number = 10,
                            Row = "2",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000021"),
                            Number = 1,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000021"),
                            Number = 1,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000022"),
                            Number = 2,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000022"),
                            Number = 2,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000023"),
                            Number = 3,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000023"),
                            Number = 3,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000024"),
                            Number = 4,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000024"),
                            Number = 4,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000025"),
                            Number = 5,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000025"),
                            Number = 5,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000026"),
                            Number = 6,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000026"),
                            Number = 6,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000027"),
                            Number = 7,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000027"),
                            Number = 7,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000028"),
                            Number = 8,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000028"),
                            Number = 8,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000029"),
                            Number = 9,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000029"),
                            Number = 9,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000030"),
                            Number = 10,
                            Row = "3",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000030"),
                            Number = 10,
                            Row = "3",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000031"),
                            Number = 1,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000031"),
                            Number = 1,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000032"),
                            Number = 2,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000032"),
                            Number = 2,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000033"),
                            Number = 3,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000033"),
                            Number = 3,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000034"),
                            Number = 4,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000034"),
                            Number = 4,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000035"),
                            Number = 5,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000035"),
                            Number = 5,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000036"),
                            Number = 6,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000036"),
                            Number = 6,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000037"),
                            Number = 7,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000037"),
                            Number = 7,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000038"),
                            Number = 8,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000038"),
                            Number = 8,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000039"),
                            Number = 9,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000039"),
                            Number = 9,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000040"),
                            Number = 10,
                            Row = "4",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000040"),
                            Number = 10,
                            Row = "4",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000041"),
                            Number = 1,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000041"),
                            Number = 1,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000042"),
                            Number = 2,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000042"),
                            Number = 2,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000043"),
                            Number = 3,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000043"),
                            Number = 3,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000044"),
                            Number = 4,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000044"),
                            Number = 4,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000045"),
                            Number = 5,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000045"),
                            Number = 5,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000046"),
                            Number = 6,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000046"),
                            Number = 6,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000047"),
                            Number = 7,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000047"),
                            Number = 7,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000048"),
                            Number = 8,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000048"),
                            Number = 8,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000049"),
                            Number = 9,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000049"),
                            Number = 9,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000050"),
                            Number = 10,
                            Row = "5",
                            SectorId = 1,
                            Status = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000050"),
                            Number = 10,
                            Row = "5",
                            SectorId = 2,
                            Status = 0,
                            Version = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Name = "VIP",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            Name = "General",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("TicketingSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TicketingSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TicketingSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TicketingSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketingSystem.Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketingSystem.Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
